news/urls.py
from django.urls import path

from news.views import news_list

app_name = 'news'
urlpatterns = [
    path('news/', news_list, name='news_list'),
]

orders/urls.py
from django.urls import path
from orders.views import OrderCreateView,SuccessTemplateView,CancelTemplateView,OrdersListView,OrderDetailView


app_name = 'orders'

urlpatterns = [
    path('order-create/', OrderCreateView.as_view(), name='order_create'),
    path('order-success/', SuccessTemplateView.as_view(), name='order_success'),
    path('order-canceled/', CancelTemplateView.as_view(), name='order_canceled'),
    path('', OrdersListView.as_view(), name='orders_list'),
    path('order/<int:pk>', OrderDetailView.as_view(), name='order'),
]

products/urls.py
from django.urls import path

from products.views import (ProductListView, basket_add, basket_delete,
                            description_product,SearchView)

app_name = 'products'

urlpatterns = [
    path('', ProductListView.as_view(), name='products'),
    path('category/<int:category_id>/', ProductListView.as_view(), name='category'),
    path('page/<int:page>/', ProductListView.as_view(), name='page'),
    path('basket-add/<int:product_id>/',basket_add,name='basket_add'),
    path('basket-delete/<int:id>/',basket_delete,name='basket_delete'),
    path('description/<int:id>/',description_product,name='description_product'),
    path('search/',SearchView.as_view(),name='search')
]

store/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from orders.views import stripe_webhook_view
from products.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(),name='index'),
    path('products/',include("products.urls",namespace='products')),
    path('users/',include("users.urls",namespace='users')),
    path('',include("news.urls",namespace='news')),
    path('orders/',include("orders.urls",namespace='orders')),
    path('stripe/webhook/', stripe_webhook_view, name='stripe_webhook'),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/models.py
from django.db import models

from products.models import Basket
from users.views import User

class Order(models.Model):
    CREATED= 0
    PAID= 1
    ON_WAY= 2
    DELIVERED= 3
    STATUES=((CREATED,'Conceived'),(PAID,'Payed'),(ON_WAY,'En route'),(DELIVERED,'Delivered'))

    first_name=models.CharField(max_length=64)
    last_name=models.CharField(max_length=64)
    email=models.EmailField(max_length=256)
    address=models.CharField(max_length=256)
    basket_history = models.JSONField(default=dict)
    created = models.DateTimeField(auto_now_add=True)
    status =models.SmallIntegerField(default=CREATED,choices=STATUES)
    initiator = models.ForeignKey(to=User,on_delete=models.CASCADE)

    def __str__(self):
        return f"Order #{self.id}.{self.first_name} - {self.last_name}"

    def update_after_payment(self):
        baskets = Basket.objects.filter(user=self.initiator)

        # Обновляем количество товаров на складе
        for basket in baskets:
            product = basket.product
            if product.quantity >= basket.quantity:
                product.quantity -= basket.quantity
                product.save()
            else:
                # Обработка случая, когда товара недостаточно на складе
                raise ValueError(f"Недостаточно товара {product.name} на складе. "
                                 f"Доступно: {product.quantity}, запрошено: {basket.quantity}")

        # Сохраняем историю покупок
        self.status = self.PAID
        self.basket_history = {
            'purchased_items': [basket.de_json() for basket in baskets],
            'total_sum': float(sum(b.sum() for b in baskets))
        }

        # Удаляем корзину после успешной покупки
        baskets.delete()
        self.save()

orders/forms.py
from django import forms

from orders.models import Order


class OrderForm(forms.ModelForm):
    first_name = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control','placeholder':'Taras'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control','placeholder':'Shevchenko'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class':'form-control','placeholder':'you@example.com'}))
    address = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control','placeholder':'Ukraine, Kyiv, Mira str., 6'}))
    class Meta:
        model =Order
        fields= ('first_name','last_name','email','address')

orders/views.py
import stripe
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView
from orders.forms import OrderForm
from django.urls import reverse_lazy,reverse
from common.views import TitleMixin
from products.models import Basket
from django.views.generic.base import TemplateView
from django.http import HttpResponseRedirect
from http import HTTPStatus
from django.http import HttpResponse
from django.conf import settings
from orders.models import Order
stripe.api_key = settings.STRIPE_SECRET_KEY
endpoint_secret = 'whsec_98ee01104284452cbd2792ee3466075bbe45776f43cc85457ed2a02028a86949'


class SuccessTemplateView(TemplateView):
    template_name = 'orders/success.html'
    title = 'ElectroHub-Thanks for order!'

class OrdersListView(TitleMixin,ListView):
    template_name = 'orders/orders.html'
    title = 'ElectroHub-orders!'
    queryset = Order.objects.filter()
    ordering = ('-created')

    def get_queryset(self):
        queryset = super(OrdersListView,self).get_queryset()
        return queryset.filter(initiator=self.request.user)

class OrderDetailView(DetailView):
    template_name = 'orders/order.html'
    model = Order

    def get_context_data(self, **kwargs):
        context = super(OrderDetailView,self).get_context_data(**kwargs)
        context['title'] = f'ElectroHub Order #{self.object.id}'
        return context

class CancelTemplateView(TitleMixin,TemplateView):
    template_name = 'orders/cancled.html'


class OrderCreateView(TitleMixin,CreateView):
    template_name = 'orders/order-create.html'
    form_class = OrderForm
    success_url = reverse_lazy('orders:order_create')
    title = 'ElectroHub-Create-order'

    def form_valid(self, form):
        form.instance.initiator =self.request.user
        return super(OrderCreateView,self).form_valid(form)

    def post(self, request, *args, **kwargs):
        response = super().post(request, *args, **kwargs)

        baskets = Basket.objects.filter(user=self.request.user)
        line_items = [{
            'price': basket.product.stripe_product_price_id,
            'quantity': basket.quantity,
        } for basket in baskets]

        checkout_session = stripe.checkout.Session.create(
            line_items=line_items,
            metadata={'order_id': str(self.object.id)},
            mode='payment',
            success_url='{}{}'.format(settings.DOMAIN_NAME, reverse('orders:order_success')),
            cancel_url='{}{}'.format(settings.DOMAIN_NAME, reverse('orders:order_canceled')),
        )

        return HttpResponseRedirect(checkout_session.url, status=HTTPStatus.SEE_OTHER)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        baskets = Basket.objects.filter(user = self.request.user)
        context['total_quantity'] = sum(b.quantity for b in baskets)
        context['total_sum'] = sum(b.sum() for b in baskets)
        return context

@csrf_exempt
def stripe_webhook_view(request):
    payload = request.body
    sig_header = request.META['HTTP_STRIPE_SIGNATURE']
    event = None

    try:
        event = stripe.Webhook.construct_event(
            payload, sig_header, settings.STRIPE_WEBHOOK_SECRET
        )
    except ValueError as e:
        # Invalid payload
        return HttpResponse(status=400)
    except stripe.error.SignatureVerificationError as e:
        # Invalid signature
        return HttpResponse(status=400)

    if (
            event['type'] == 'checkout.session.completed'
            or event['type'] == 'checkout.session.async_payment_succeeded'
    ):
        fulfill_order(session=event['data']['object'])

    return HttpResponse(status=200)

def fulfill_order(session):
    order_id = int(session.metadata.order_id)
    order = Order.objects.get(id=order_id)
    order.update_after_payment()

orders/templates/orders/cancled.html
<!DOCTYPE html>
<html>
<head>
  <title>Checkout canceled</title>
  <link rel="stylesheet" href="style.css">
</head>
<body>
  <section>
    <p>Forgot to add something to your cart? Shop around then come back to pay!</p>
  </section>
</body>
</html>

orders/templates/orders/order-create.html
{%extends 'products/base.html'%}
{%load %}

{%block content%}
<section>
    <div class="alert alert-warning text-center" role="alert">
        Пожалуйста, заполните адрес электронной почты.
    </div>
    <div class="container">
        <div class="py-5 text-center">
            <h1>Order placement</h1>
        </div>
        <div class="row g-5">
            <div class="col-md-5 col-lg-4 order-md-last">
                <h4 class="d-flex justify-content-between align-items-center mb-3">
                    <span class="text-primary">Basket</span>
                    <span class="badge badge-primary badge-pill text-white">{{total_quantity}}</span>
                </h4>
                <ul class="list-group mb-3">
                    {%for basket in baskets %}
                        <li class="list-group-item d-flex justify-content-between lh-sm">
                            <div>
                                <h6 class="my-0">{{basket.product.name}}</h6>
                                <small class="text-muted">{{basket.quantity}} quan.</small>
                            </div>
                            <span class="text-muted">{{basket.sum}} UAH.</span>
                        </li>
                    {% endfor %}
                    <li class="list-group-item d-flex justify-content-between">
                        <span>Total</span>
                        <strong>{{total_sum}} UAH.</strong>
                    </li>
                </ul>
            </div>
            <div class="col-md-7 col-lg-8">
                <h4 class="mb-3">Delivery address</h4>
                <form action="{%url 'orders:order_create'%}" method="post">
                    {%csrf_token%}
                    <div class="row g-3">
                        <div class="col-sm-6">
                            <label for="form.first_name.id_for_label" class="form-label">Name</label>
                            {{form.first_name}}
                        </div>

                        <div class="col-sm-6">
                            <label for="form.last_name.id_for_label" class="form-label">Surname</label>
                            {{form.last_name}}
                        </div>

                        <div class="col-12 mt-3">
                            <label for="form.email.id_for_label" class="form-label">Email address</label>
                            {{form.email}}
                        </div>

                        <div class="col-12 mt-3">
                            <label for="form.address.id_for_label" class="form-label">Address</label>
                            {{form.address}}
                        </div>

                    </div>

                    <hr class="my-4">

                    <button class="w-100 btn btn-primary btn-lg" type="submit">To be continued</button>
                </form>
            </div>
        </div>
    </div>
</section>
{%endblock%}
<!-- Page Content -->

orders/templates/orders/order.html
{%extends 'products/base.html'%}

{%block content%}<section>
    <div class="container pt-5">
        <div class="text-center mt-5">
            <h1>Order {{object.id}}</h1>
            <div class="orders mt-5">
                <table class="table">
                    <thead>
                    <tr>
                        <th scope="col">Name</th>
                         <th scope="col">Quantity</th>
                         <th scope="col">Price</th>
                         <th scope="col">Amount</th>
                    </tr>
                    </thead>
                    <tbody>
                    {%for purchased_item in object.basket_history.purchased_items %}
                        <tr>
                            <th scope="row">
                                {{purchased_item.product_name}}
                            </th>
                            <td>{{purchased_item.quantity}}</td>
                            <td>{{purchased_item.price}} UAH.</td>
                            <td>{{purchased_item.sum}} UAH.</td>
                        </tr>
                    {%endfor%}

                    </tbody>
                </table>
                <p class="float-right h4 mt-3">{{object.basket_history.total_sum}} UAH.</p>
            </div>
        </div>
    </div>
</section>
{%endblock%}

orders/templates/orders/orders.html
{%extends 'products/base.html'%}

{%block content%}
<section>
    <div class="container pt-5">
        <div class="text-center mt-5">
            <h1>Orders</h1>
            <div class="orders mt-5">
                <table class="table">
                    <thead>
                    <tr class="table-light">
                        <th scope="col">#</th>
                        <th scope="col">Status</th>
                        <th scope="col">Created</th>
                        <th scope="col">Total</th>
                        <th scope="col">Action</th>
                    </tr>
                    </thead>
                    <tbody>
                    {%for order in object_list%}
                        <tr class="">
                            <th scope="row">{{order.id}}</th>
                            <td>{{order.get_status_display}}</td>
                            <td>{{order.created}}</td>
                            <td>{{order.basket_history.total_sum}} UAH</td>
                            <td>
                                <a href="{% url 'orders:order' order.id %}">view</a>
                            </td>
                        </tr>
                    {%endfor%}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</section>
{%endblock%}

orders/templates/orders/success.html
{%extends 'users/base.html'%}

{%block content%}
<main>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-9">
                <div class="card shadow-lg border-0 rounded-lg mt-5">
                    <div class="card-header">
                        <h3 class="text-center font-weight-light my-4">Congratulations</h3>
                    </div>
                    <div class="card-body text-center">
                        <h4 class="text-break">Your payment has been successfully paid!</h4>
                    </div>
                    <div class="card-footer text-center">
                        <div class="small">
                            <a href="{% url "products:products" %}">To be continued</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>
{%endblock%}