news/urls.py
from django.urls import path

from news.views import news_list

app_name = 'news'
urlpatterns = [
    path('news/', news_list, name='news_list'),
]

products/urls.py
from django.urls import path

from products.views import (ProductListView, basket_add, basket_delete,
                            description_product,SearchView)

app_name = 'products'

urlpatterns = [
    path('', ProductListView.as_view(), name='products'),
    path('category/<int:category_id>/', ProductListView.as_view(), name='category'),
    path('page/<int:page>/', ProductListView.as_view(), name='page'),
    path('basket-add/<int:product_id>/',basket_add,name='basket_add'),
    path('basket-delete/<int:id>/',basket_delete,name='basket_delete'),
    path('description/<int:id>/',description_product,name='description_product'),
    path('search/',SearchView.as_view(),name='search')
]

store/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from orders.views import stripe_webhook_view
from products.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(),name='index'),
    path('products/',include("products.urls",namespace='products')),
    path('users/',include("users.urls",namespace='users')),
    path('',include("news.urls",namespace='news')),
    path('orders/',include("orders.urls",namespace='orders')),
    path('stripe/webhook/', stripe_webhook_view, name='stripe_webhook'),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path, reverse_lazy
from .views import login, profile, logout, UserRegistrationView, EmailVerificationView, MyPasswordResetView,MyPasswordResetForm, MyPasswordResetConfirmView
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView

app_name = 'users'  # Эта строка нужна для работы namespace!

urlpatterns = [
    path('login/', login, name='login'),
    path('register/', UserRegistrationView.as_view(), name='register'),
    path('profile/', profile, name='profile'),
    path('logout/', logout, name='logout'),
    path(
        'password-reset/',
        MyPasswordResetView.as_view(
            template_name='users/password_reset_form.html',
            email_template_name='users/password_reset_email.html',
            success_url=reverse_lazy('users:password_reset_done')
        ),
        name="password_reset"
    ),
    path(
        'password-reset/done/',
        PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
        name="password_reset_done"
    ),
    path(
        'password-reset/<uidb64>/<token>/',
        MyPasswordResetConfirmView.as_view(
            template_name='users/password_reset_confirm.html',
            success_url=reverse_lazy('users:password_reset_complete')
        ),
        name="password_reset_confirm"
    ),
    path(
        'password-reset/complete/',
        PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
        name="password_reset_complete"
    ),
    path(
        'verify/<str:email>/<uuid:code>/',
        EmailVerificationView.as_view(),
        name='email_verifications'
    ),
]

users/models.py
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.core.mail import send_mail
from django.db import models
from django.urls import reverse
from django.utils.timezone import now


class User(AbstractUser):
    image = models.ImageField(upload_to='users_images', blank=True)
    is_verified_email = models.BooleanField(default=False)
    email = models.EmailField(unique=True)


class EmailVerification(models.Model):
    code = models.UUIDField(unique=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    expiration = models.DateTimeField()

    def __str__(self):
        return f'Emailverification for {self.user.email}'

    def send_verification_email(self):
        link = reverse('users:email_verifications', kwargs={'email': self.user.email, 'code': self.code})
        verification_link = f'{settings.DOMAIN_NAME}{link}'
        subject = f'Account confirmation for {self.user.username}'
        message = 'To confirm the account for {} follow this link {}'.format(self.user.email, verification_link)
        send_mail(
            subject=subject,
            message=message,
            from_email=settings.EMAIL_HOST_USER,
            recipient_list=[self.user.email],
            fail_silently=False
        )

    def is_expired(self):
        return True if now() >= self.expiration else False

users/forms.py
import uuid
from datetime import timedelta

from django import forms
from django.contrib.auth.forms import (AuthenticationForm, UserChangeForm,
                                       UserCreationForm, PasswordResetForm, SetPasswordForm)
from django.utils.timezone import now

from users.models import EmailVerification, User


class UserLoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={"placeholder": 'Enter your user name'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={"placeholder": 'Enter your password'}))

    class Meta:
        model = User
        fields = ('username', 'password')

    def __init__(self, *args, **kwargs):
        super(UserLoginForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = "form-control py-4"


class UserRegistrationForm(UserCreationForm):
    first_name = forms.CharField(widget=forms.TextInput(attrs={'placeholder': "Enter a name"}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={'placeholder': "Enter last name"}))
    username = forms.CharField(widget=forms.TextInput(attrs={'placeholder': "Enter your user name"}))
    email = forms.CharField(widget=forms.EmailInput(attrs={'placeholder': "Enter your e-mail address"}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': "Enter your password"}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': "Confirm password"}))

    class Meta:
        model = User
        fields = ("first_name", 'last_name', 'username', 'email', 'password1', 'password2')

    def save(self, commit=True):
        user = super(UserRegistrationForm, self).save(commit=True)
        expiration = now() + timedelta(hours=48)
        recored = EmailVerification.objects.create(code=uuid.uuid4(), user=user, expiration=expiration)
        recored.send_verification_email()
        return user

    def __init__(self, *args, **kwargs):
        super(UserRegistrationForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = "form-control py-4"


class UserProfileForm(UserChangeForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'readonly': True}))
    email = forms.CharField(widget=forms.EmailInput(attrs={'readonly': True}))
    image = forms.ImageField(widget=forms.FileInput(), required=False)

    class Meta:
        model = User
        fields = ('username', 'email', "first_name", 'last_name', 'image')

    def __init__(self, *args, **kwargs):
        super(UserProfileForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = "form-control py-4"
        self.fields['image'].widget.attrs['class'] = 'custom-file-input'

class MyPasswordResetForm(PasswordResetForm):
    email = forms.EmailField(widget=forms.EmailInput(attrs={
        'class': 'form-control py-4',
        'placeholder': 'Enter your e-mail address'
    }))

class MyPasswordResetConfirmForm(SetPasswordForm):
    new_password1 = forms.CharField(
        label="New password",
        widget=forms.PasswordInput(attrs={'placeholder': "Enter your password", 'class': 'form-control py-4'})
    )
    new_password2 = forms.CharField(
        label="Confirm new password",
        widget=forms.PasswordInput(attrs={'placeholder': "Confirm password", 'class': 'form-control py-4'})
    )

users/views.py
from django.contrib import auth
from django.contrib.auth.forms import SetPasswordForm
from django.contrib.auth.views import PasswordResetView, PasswordResetConfirmView
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import HttpResponseRedirect, render
from django.urls import reverse, reverse_lazy
from django.views.generic.base import TemplateView
from django.views.generic.edit import CreateView

from common.views import TitleMixin
from products.models import Basket
from users.forms import UserLoginForm, UserProfileForm, UserRegistrationForm, MyPasswordResetForm, MyPasswordResetConfirmForm
from users.models import EmailVerification, User


def login(request):
    if request.method == 'POST':
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            username = request.POST["username"]
            password = request.POST['password']
            user = auth.authenticate(username=username, password=password)
            if user and user.is_active:
                auth.login(request, user)
                return HttpResponseRedirect(reverse('index'))
    else:
        form = UserLoginForm()
    context = {'title': 'ElectroHub - Authorization', 'form': form}
    return render(request, 'users/login.html', context)


class UserRegistrationView(TitleMixin, SuccessMessageMixin, CreateView):
    model = User
    form_class = UserRegistrationForm
    title = 'ElectroHub - Registration'
    template_name = 'users/register.html'
    success_url = reverse_lazy('users:login')
    success_message = 'You have successfully checked in!'

    def get_context_data(self, **kwargs):
        context = super(UserRegistrationView, self).get_context_data(**kwargs)
        return context


def profile(request):
    user = request.user
    if request.method == 'POST':
        form = UserProfileForm(data=request.POST, instance=user, files=request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('users:profile'))
    else:
        form = UserProfileForm(instance=user)
    baskets = Basket.objects.filter(user=user)
    total_quantity = sum(basket.quantity for basket in baskets)
    total_sum = sum(basket.sum() for basket in baskets)
    context = {'title': 'ElectroHub - Profile',
               'form': form,
               'baskets': baskets,
               'total_quantity': total_quantity,
               'total_sum': total_sum}
    return render(request, 'users/profile.html', context)


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('index'))


class EmailVerificationView(TitleMixin, TemplateView):
    title = 'ElectroHub - Email Confirmation'
    template_name = 'users/email_verification.html'

    def get(self, request, *args, **kwargs):
        code = kwargs['code']
        user = User.objects.get(email=kwargs['email'])
        email_verifications = EmailVerification.objects.filter(user=user, code=code)

        if email_verifications.exists() and not email_verifications.first().is_expired():
            user.is_verified_email = True
            user.save()
            return super(EmailVerificationView, self).get(request, *args, **kwargs)
        else:
            return HttpResponseRedirect(reverse('index'))


class MyPasswordResetView(PasswordResetView):
    template_name = 'registration/password_reset_form.html'  # твой шаблон
    form_class = MyPasswordResetForm  # если кастомная форма с красивыми полями

class MyPasswordResetConfirmView(PasswordResetConfirmView):
    template_name = 'registration/password_reset_confirm.html'  # твой шаблон
    form_class = MyPasswordResetConfirmForm  # если кастомная форма с красивыми полями

users/templates/users/base.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <title>{{title|title}}</title>
    <link href="{%static 'css/auth.css'%}" rel="stylesheet"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/js/all.min.js"
            crossorigin="anonymous"></script>
</head>
<body class="bg-primary">
<div id="layoutAuthentication">
    <div id="layoutAuthentication_content">
        <main>
            <div class="container">
                <div class="row justify-content-center">
                    {%block content%}{%endblock%}
                </div>
            </div>
        </main>
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
        crossorigin="anonymous"></script>
<script src="{% static 'js/auth.js'%}"></script>
</body>
</html>

users/templates/users/email_verification.html
{% extends 'users/base.html' %}

{% block content %}
<main>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-9">
                <div class="card shadow-lg border-0 rounded-lg mt-5">
                    <div class="card-header">
                        <h3 class="text-center font-weight-light my-4">Congratulations</h3>
                    </div>
                    <div class="card-body text-center">
                        <h4 class="text-break">Your account has been successfully verified!</h4>
                    </div>
                    <div class="card-footer text-center">
                        <div class="small">
                            <a href="{% url "products:products" %}">To be continued</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>
{% endblock %}

users/templates/users/login.html
{%extends 'users/base.html'%}
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <title> ElectroHub - Authorization </title>
    <link href="{%static 'css/auth.css'%}" rel="stylesheet"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/js/all.min.js"
            crossorigin="anonymous"></script>
{%block content%}
    <div class="col-lg-5">
        {% if messages or form.errors %}
                <div class="alert 
                {% if messages %} 
                    alert-success 
                {% else %} 
                    alert-warning 
                {% endif %} 
                alert-dismissible fade show" 
                role="alert" 
                style="margin-top: 50px;">
                {% if messages %}
                    {% for message in messages %}
                        {{ message }}
                    {% endfor %}
                {% else %}
                    {{ form.non_field_errors }}
                {% endif %}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        {% endif %}
        <div class="card shadow-lg border-0 rounded-lg mt-5">
            <div class="card-header"><h3 class="text-center font-weight-light my-4"> Authorization</h3>
            </div>
            <div class="card-body">
                <form action="{%url 'users:login'%}" method="post">
                    {% csrf_token%}
                    <div class="form-group">
                        <label class="small mb-1" for="{{form.username.id_for_label}}">User Name</label>
                        {{form.username}}
                    </div>
                    <div class="form-group">
                        <label class="small mb-1" for="{{form.password.id_for_label}}">Password</label>
                        {{form.password}}
                    </div>
                    <div class="form-group d-flex align-items-center justify-content-between mt-4 mb-0">
                        <a class="small" href="{%url 'users:password_reset' %}"> Forgot your password?</a>
                        <input class="btn btn-primary" type="submit" value="Sign in">
                    </div> 
                </form>
            </div>
            <div class="card-footer text-center">
                <div class="small"><a href="{%url 'users:register'%}"> Need an account? Sign up!</a></div>
            </div>
        </div>
    </div>
{%endblock%}

users/templates/users/password_reset_complete.html
{% extends 'users/base.html' %}

{% block content %}
<main>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-9">
                <div class="card shadow-lg border-0 rounded-lg mt-5">
                    <div class="card-header">
                        <h3 class="text-center font-weight-light my-4">Congratulations</h3>
                    </div>
                    <div class="card-body text-center">
                        <h4 class="text-break">You have just changed your password successfully!</h4>
                    </div>
                    <div class="card-footer text-center">
                        <div class="small">
                            <a href="{% url "users:login" %}">To be continued</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>
{% endblock %}

users/templates/users/password_reset_confirm.html
{%extends 'users/base.html'%}
{%load static%}

{%block content%}
    <div class="col-lg-5">
        {% if messages or form.errors %}
                <div class="alert
                {% if messages %}
                    alert-success
                {% else %}
                    alert-warning
                {% endif %}
                alert-dismissible fade show"
                role="alert"
                style="margin-top: 50px;">
                {% if messages %}
                    {% for message in messages %}
                        {{ message }}
                    {% endfor %}
                {% else %}
                    {{ form.non_field_errors }}
                {% endif %}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        {% endif %}
        <div class="card shadow-lg border-0 rounded-lg mt-5">
            <div class="card-header"><h3 class="text-center font-weight-light my-4"> Setting up new password</h3>
            </div>
            <div class="card-body">
                <form method="post">
                    {% csrf_token%}
                     <div class="col-md-6">
                        <div class="form-group">
                            <label class="small mb-1" for="{{form.password1.id_for_label}}">Password</label>
                            {{form.new_password1}}
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label class="small mb-1" for="{{form.password2.id_for_label}}">Password confirmation</label>
                            {{form.new_password2}}
                        </div>
                    </div>
                    <div class="form-group d-flex align-items-center justify-content-between mt-4 mb-0">
                        <input class="btn btn-primary" type="submit" value="Save">
                    </div>
                </form>
            </div>
        </div>
    </div>
{%endblock%}

users/templates/users/password_reset_done.html
{% extends 'users/base.html' %}

{% block content %}
<main>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-9">
                <div class="card shadow-lg border-0 rounded-lg mt-5">
                    <div class="card-header">
                        <h3 class="text-center font-weight-light my-4">Check Your Email</h3>
                    </div>
                    <div class="card-body text-center">
                        <h4 class="text-break">We have sent you an email with instructions to reset your password.</h4>
                    </div>
                    <div class="card-footer text-center">
                        <div class="small">
                            <a href="{% url "products:products" %}">Return to Home</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>
{% endblock %}

users/templates/users/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% translate 'In case you’ve forgotten, you are:' %} {{ user.get_username }}

{% translate "Thanks for using our site!" %}

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}

users/templates/users/password_reset_form.html
{%extends 'users/base.html'%}
{%load static%}

{%block content%}
    <div class="col-lg-5">
        {% if messages or form.errors %}
                <div class="alert
                {% if messages %}
                    alert-success
                {% else %}
                    alert-warning
                {% endif %}
                alert-dismissible fade show"
                role="alert"
                style="margin-top: 50px;">
                {% if messages %}
                    {% for message in messages %}
                        {{ message }}
                    {% endfor %}
                {% else %}
                    {{ form.non_field_errors }}
                {% endif %}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        {% endif %}
        <div class="card shadow-lg border-0 rounded-lg mt-5">
            <div class="card-header"><h3 class="text-center font-weight-light my-4">Reset password</h3>
            </div>
            <div class="card-body">
                <form method="post">
                    {% csrf_token%}
                    <div class="form-group">
                        <label class="small mb-1" for="{{form.email.id_for_label}}">Email</label>
                        {{form.email}}
                    </div>
                    <div class="form-group d-flex align-items-center justify-content-between mt-4 mb-0">
                        <input class="btn btn-primary" type="submit" value="Send message">
                    </div>
                </form>
            </div>
            <div class="card-footer text-center">
                <div class="small"><a href="{%url 'users:register'%}"> Need an account? Sign up!</a></div>
            </div>
        </div>
    </div>
{%endblock%}

users/templates/users/profile.html
{%extends 'products/base.html'%}
{%load static%}

{%block css%}
    <link href="{%static 'css/profile.css'%}" rel="stylesheet">
{%endblock%}

{%block content%}
<div class="container">
    <div class="row">
        <div class="col-lg-7">
            <h4 class="mt-3 mb-3">Profile</h4>
            <div class="col-lg-12 text-center">
                <img width="100" height="100"
                     src="{%if user.image%} {{user.image.url}} {%else %} {% static 'vendor/img/users/default_ava.jpg'%} {%endif%}"
                     class="img-thumbnail">
            </div>
            <form action="{%url 'users:profile'  %} " method="post" enctype="multipart/form-data">
                {%csrf_token%}
                <div class="form-row">
                    <div class="col-lg-6">
                        <div class="form-group">
                            <label class="small mb-1" for="{{form.first_name.id_for_label}}">Name</label>
                            {{form.first_name}}
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="form-group">
                            <label class="small mb-1" for="{{form.last_name.id_for_label}}">Surname</label>
                            {{form.last_name}}
                        </div>
                    </div>
                </div>
                <div class="form-row mb-2">
                    <div class="col-lg-12">
                        <div class="custom-file">
                            {{form.image}}
                            <label class="custom-file-label" for="{{form.image.id_for_label}}">Select an image
                            </label>
                        </div>
                    </div>
                </div>
                <div class="form-row">
                    <div class="col-lg-6">
                        <label class="small mb-1" for="{{form.username.id_for_label}}">Username</label>
                        {{form.username}}
                    </div>
                    <div class="col-lg-6">
                        <label class="small mb-1" for="{{form.email.id_for_label}}">E-mail address</label>
                        {{form.email}}
                    </div>
                </div>
                <div class="form-row">
                    <div class="col-lg-12" style="margin-top: 33px;">
                        <input class="btn btn-info btn-block" type="submit" value="Save">
                    </div>
                </div>
                {%for msg in messages%}
                <div class="alert {%if msg.tags == 'success' %}alert-success{%elif msg.tags == 'error'%}alert-warning {%endif%} alert-dismissible fade show" role="alert" style="margin-top: 20px;">
                    {{msg}}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close" onclick="this.parentElement.style.display='none';">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            {%endfor%}
            </form>
        </div>
        {%include 'products/basket.html'%}
    </div>
</div>
{%endblock%}

users/templates/users/register.html
{%extends 'users/base.html'%}
{%load static%}

{%block content%}
<div class="col-lg-7">
    {%if form.errors%}
        <div class="alert alert-warning alert-dismissible fade show" role="alert"
            style="margin-top: 50px;">
            {{form.errors}}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    {%endif%}
    <div class="card shadow-lg border-0 rounded-lg mt-5">
        <div class="card-header"><h3 class="text-center font-weight-light my-4">Create an account</h3>
        </div>
        <div class="card-body">
            <form action="{%url 'users:register'%}" method="post">
                {% csrf_token %}
                <div class="form-row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label class="small mb-1" for="{{ form.first_name.id_for_label }}">Name</label>
                            {{ form.first_name }}
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label class="small mb-1" for="{{form.last_name.id_for_label}}">Surname</label>
                            {{form.last_name}}
                        </div>
                    </div>
                </div>
                <div class="form-row">
                    <div class="col-md-6">
                        <label class="small mb-1" for="{{form.username.id_for_label}}">User Name</label>
                        {{form.username }}
                    </div>
                    <div class="col-md-6">
                        <label class="small mb-1" for="{{form.email.id_for_label}}">E-mail address</label>
                        {{form.email}}
                    </div>
                </div>
                <div class="form-row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label class="small mb-1" for="{{form.password1.id_for_label}}">Password</label>
                            {{form.password1}}
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label class="small mb-1" for="{{form.password2.id_for_label}}">Password confirmation</label>
                            {{form.password2}}
                        </div>
                    </div>
                </div>
                <div class="form-group mt-4 mb-0">
                    <input class="btn btn-primary btn-block" type="submit" value="Create an account">
                </div>
            </form>
        </div>
        <div class="card-footer text-center">
            <div class="small"><a href="{%url 'users:login'%}">Already have an account? Authorize</a></div>
        </div>
    </div>
</div>
{%endblock%}
                