news/urls.py
from django.urls import path

from news.views import news_list

app_name = 'news'
urlpatterns = [
    path('news/', news_list, name='news_list'),
]

orders/urls.py
from django.urls import path
from orders.views import OrderCreateView,SuccessTemplateView,CancelTemplateView,OrdersListView,OrderDetailView


app_name = 'orders'

urlpatterns = [
    path('order-create/', OrderCreateView.as_view(), name='order_create'),
    path('order-success/', SuccessTemplateView.as_view(), name='order_success'),
    path('order-canceled/', CancelTemplateView.as_view(), name='order_canceled'),
    path('', OrdersListView.as_view(), name='orders_list'),
    path('order/<int:pk>', OrderDetailView.as_view(), name='order'),
]

products/urls.py
from django.urls import path

from products.views import (ProductListView, basket_add, basket_delete,
                            description_product,SearchView)

app_name = 'products'

urlpatterns = [
    path('', ProductListView.as_view(), name='products'),
    path('category/<int:category_id>/', ProductListView.as_view(), name='category'),
    path('page/<int:page>/', ProductListView.as_view(), name='page'),
    path('basket-add/<int:product_id>/',basket_add,name='basket_add'),
    path('basket-delete/<int:id>/',basket_delete,name='basket_delete'),
    path('description/<int:id>/',description_product,name='description_product'),
    path('search/',SearchView.as_view(),name='search')
]

store/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from orders.views import stripe_webhook_view
from products.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(),name='index'),
    path('products/',include("products.urls",namespace='products')),
    path('users/',include("users.urls",namespace='users')),
    path('',include("news.urls",namespace='news')),
    path('orders/',include("orders.urls",namespace='orders')),
    path('stripe/webhook/', stripe_webhook_view, name='stripe_webhook'),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path, reverse_lazy
from .views import login, profile, logout, UserRegistrationView, EmailVerificationView, MyPasswordResetView,MyPasswordResetForm, MyPasswordResetConfirmView
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView

app_name = 'users'  # Эта строка нужна для работы namespace!

urlpatterns = [
    path('login/', login, name='login'),
    path('register/', UserRegistrationView.as_view(), name='register'),
    path('profile/', profile, name='profile'),
    path('logout/', logout, name='logout'),
    path(
        'password-reset/',
        MyPasswordResetView.as_view(
            template_name='users/password_reset_form.html',
            email_template_name='users/password_reset_email.html',
            success_url=reverse_lazy('users:password_reset_done')
        ),
        name="password_reset"
    ),
    path(
        'password-reset/done/',
        PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
        name="password_reset_done"
    ),
    path(
        'password-reset/<uidb64>/<token>/',
        MyPasswordResetConfirmView.as_view(
            template_name='users/password_reset_confirm.html',
            success_url=reverse_lazy('users:password_reset_complete')
        ),
        name="password_reset_confirm"
    ),
    path(
        'password-reset/complete/',
        PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
        name="password_reset_complete"
    ),
    path(
        'verify/<str:email>/<uuid:code>/',
        EmailVerificationView.as_view(),
        name='email_verifications'
    ),
]

products/models.py
from locale import currency

from django.db import models
import stripe
from users.models import User
from django.conf import settings

stripe.api_key=settings.STRIPE_SECRET_KEY

class ProductCategory(models.Model):
    name = models.CharField(max_length=64, unique=True)
    description = models.TextField(blank=True)

    def __str__(self):
        return f"{self. name}"

    class Meta:
        verbose_name_plural = 'Product Categories'


class Product(models.Model):
    name = models.CharField(max_length=256)
    image = models.ImageField(upload_to='products_images', blank=True)
    description = models.TextField(blank=True)
    short_description = models.CharField(max_length=64, blank=True)
    price = models.DecimalField(max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveBigIntegerField(default=0)
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    characteristics = models.JSONField(default=dict, blank=True)
    stripe_product_price_id = models.CharField(max_length=128,null=True,blank=True)


    def __str__(self):
        return f"{self. name}|{self.category.name}"


    def save(self,force_insert=False,force_update=False,using=None,update_fields=None):
        if not self.stripe_product_price_id:
            stripe_product_price =self.create_stripe_product_price()
            self.stripe_product_price_id =stripe_product_price['id']
        super(Product, self).save(force_insert=False, force_update=False, using=using, update_fields=update_fields)

    def create_stripe_product_price(self):
        stripe_product =stripe.Product.create(name=self.name)
        stripe_product_price= stripe.Price.create(product=stripe_product['id'],unit_amount= round(self.price *100),currency='uah')
        return stripe_product_price


class Basket(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=0)
    created_timestap = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Basket for {self.user.username} | Product {self.product.name}"

    def sum(self):
        res = self.quantity * self.product.price
        return res

    def de_json(self):
        basket_item ={
            'product_name':self.product.name,
            'quantity':self.quantity,
            'price':float(self.product.price),
            'sum':float(self.sum())
        }
        return basket_item

products/views.py
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.shortcuts import HttpResponseRedirect, render
from django.views.generic.base import TemplateView
from django.views.generic.list import ListView
from django.contrib import messages
from common.views import TitleMixin
from products.models import Basket, Product, ProductCategory


class IndexView(TitleMixin, TemplateView):
    template_name = "products/index.html"
    title = 'ElectroHub'

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data()

        return context


class ProductListView(TitleMixin,ListView):
    title = 'Catalog'
    model = Product
    template_name = 'products/products.html'
    context_object_name = 'object_list'
    paginate_by = 9

    def get_queryset(self):
        queryset = Product.objects.all()

        category_id = self.request.GET.get('category')
        if category_id:
            queryset = queryset.filter(category_id=category_id)

        price_min = self.request.GET.get('price_min')
        price_max = self.request.GET.get('price_max')
        price_range = self.request.GET.get('price_range')

        if price_range:
            if '-' in price_range:
                min_val, max_val = price_range.split('-')
                if min_val:
                    queryset = queryset.filter(price__gte=int(min_val))
                if max_val:
                    queryset = queryset.filter(price__lte=int(max_val))
            else:
                queryset = queryset.filter(price__gte=int(price_range.replace('-', '')))

        if price_min:
            queryset = queryset.filter(price__gte=price_min)
        if price_max:
            queryset = queryset.filter(price__lte=price_max)

        brands = self.request.GET.getlist('brands')
        if brands:
            queryset = queryset.filter(brand_id__in=brands)

        if self.request.GET.get('in_stock'):
            queryset = queryset.filter(quantity__gt=0)

        if self.request.GET.get('on_sale'):
            queryset = queryset.filter(discount__gt=0)

        search = self.request.GET.get('search')
        if search:
            queryset = queryset.filter(
                Q(name__icontains=search) |
                Q(short_description__icontains=search)
            )

        sort = self.request.GET.get('sort')
        if sort == 'price_asc':
            queryset = queryset.order_by('price')
        elif sort == 'price_desc':
            queryset = queryset.order_by('-price')
        elif sort == 'name_asc':
            queryset = queryset.order_by('name')
        elif sort == 'name_desc':
            queryset = queryset.order_by('-name')
        elif sort == 'newest':
            queryset = queryset.order_by('-created_at')
        else:
            queryset = queryset.order_by('id')

        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = ProductCategory.objects.all()
        return context



@login_required
def basket_add(request, product_id):
    current_page = request.META.get('HTTP_REFERER')
    product = Product.objects.get(id=product_id)
    baskets = Basket.objects.filter(user=request.user, product=product)

    if not baskets.exists():
        Basket.objects.create(user=request.user, product=product, quantity=1)
        messages.success(request, 'Product added to basket')
        return HttpResponseRedirect(current_page)
    else:
        basket = baskets.first()
        if basket.quantity < product.quantity:
            basket.quantity += 1
            messages.success(request, 'Product added to basket')
            basket.save()
        else: messages.error(request, 'Out of stock')
        return HttpResponseRedirect(current_page)
        


@login_required
def basket_delete(request, id):
    basket = Basket.objects.get(id=id)
    if basket.quantity > 1:
        basket.quantity -= 1
        basket.save()
    else:
        basket.delete()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


def description_product(request, id):
    context = {'product': Product.objects.get(id=id)}
    return render(request, 'products/description_product.html', context)

class SearchView(TitleMixin, ListView):
    model = Product
    template_name = 'products/products.html'
    paginate_by = 6
    
    def get_queryset(self):
       return Product.objects.filter(name__icontains=self.request.GET.get('q'))
   
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['q']=self.request.GET.get('q')  
        return context
   

products/templates/products/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{{title|title}}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link rel = 'icon' href="{% static 'vendor/img/logo.icon' %}">

    <!-- Custom styles for this template -->
    {%block css%}
    {%endblock%}


</head>

<body>

<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
        <a class="navbar-brand" href="{%url 'index'%}">ElectroHub
            <img src="{% static 'vendor/img/logo.icon' %} " width="30" height="30" alt="logo of store">
        </a>

        <div class="collapse navbar-collapse" id="navbarResponsive">
            <form class="d-flex" role="search" method="get" action="{% url 'products:search'%}">
                {% csrf_token %}
                <input class="form-control me-2" type="search" name="q" placeholder="Search..." aria-label="Search">
                <button class="btn btn-outline-success" type="submit">
                    <i class="fas fa-search"></i>
                </button>
            </form>
            <button class="btn btn-outline-light navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"></button>
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{%url 'products:products'%}">Catalog <i class="fas fa-th-large"></i> </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link " href="{%url 'news:news_list'%}">News <i class="fas fa-rss"></i> </a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">
                        <i class="fas fa-user-circle"></i>
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        {% if user.is_authenticated %}
                            <li>
                                <a class="dropdown-item" href="{%url 'users:profile'%}">Profile</a>
                            </li>
                            <li><a class="dropdown-item" href="{%url 'orders:orders_list'%}">Orders</a></li>
                            {%if user.is_superuser %}
                                <li><a class="dropdown-item" href="{% url 'admin:index' %}">Admin-panel</a></li>
                            {%endif%}
                            <li>
                                <hr class="dropdown-divider">
                            </li>
                            <li>
                                <a class="dropdown-item" href="{% url 'users:logout' %}">
                                    Exit
                                </a>
                            </li>
                        {% else %}
                            <li><a class="dropdown-item" href="{% url 'users:login' %}">Sign in</a></li>
                        {%endif%}
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>

<!-- Page Content -->
{% block content%}
{%endblock%}
{%block footer%}
{%endblock%}


<!-- Bootstrap core JavaScript -->
<script src="{% static 'vendor/jquery/jquery.min.js' % }"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js'%}"></script>

<!-- FontAwesome script -->
<script src="{%static 'vendor/fontawesome/fontawesome-icons.js'%}" crossorigin="anonymous"></script>

</body>

</html>

products/templates/products/basket.html
{%if baskets%}
    <div class="col-lg-5">
        <h4 class="mt-3 mb-3 d-flex justify-content-between align-items-center mb-3">
            Basket <span class="badge badge-secondary badge-pill">{{total_quantity}}</span>
        </h4>
        {%for basket in baskets%}
            <div class="card mb-3">
                <div class="card-body">
                    <h5 class="card-title">{{basket.product.name}}</h5>
                    <p class="card-text">{{basket.product.short_description}}</p>
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item d-flex justify-content-between lh-condensed bg-light">
                        <span class="text-muted">{{basket.quantity}} quan.</span>
                        <span class="text-muted">{{basket.sum}} UAH</span>
                        <span class="text-muted">
                            <a href="{%url 'products:basket_add' basket.product.id %}" style="text-decoration: none; color: gray;">
                                <i class="fas fa-cart-plus"></i>
                            </a>
                            <a href="{%url 'products:basket_delete' basket.id %}" style="text-decoration: none; color: gray;">
                                <i class="far fa-trash-alt"></i>
                            </a>
                        </span>
                    </li>
                </ul>
            </div>
        {%endfor%}
        
        <div class="card mb-3">
            <div class="card-footer">
                <p class="float-left">Total </p>
                <h4 class="float-right">{{total_sum}} UAH</h4>
            </div>
        </div>
        <a class="btn btn-success btn-lg float-right" href="{%url 'orders:order_create'%}">Finalise</a>
    </div>
{%else%}
<h4 class="mt-3 mb-3 text-center">
    Basket is empty
</h4>
{%endif%}

products/templates/products/description_product.html
{% extends "products/base.html" %}

{% block content %}

{% if messages %}
<div id="alert-container" style="position: fixed; top: 100px; right: 20px; z-index: 1050; width: 350px;">
    {% for msg in messages %}
        <div class="alert {% if msg.tags == 'success' %}alert-success{% elif msg.tags == 'error' %}alert-warning{% endif %} alert-dismissible fade show" role="alert">
            {{ msg }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close" onclick="this.parentElement.style.display='none';">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    {% endfor %}
</div>
{% endif %}

<div class="container-fluid py-4" style="margin-top: 50px;">
    <div class="row g-4">
        <div class="col-lg-6">
            <div class="product-image-container position-relative">
                <img src="/media/{{ product.image }}"
                     alt="{{ product.name }}"
                     class="img-fluid rounded-3 shadow-sm main-product-image"
                     style="width: 60%; height: 500px; object-fit: cover;margin-left:200px;margin-top:50px;">
            </div>
        </div>

        <div class="col-lg-6">
            <div class="product-details">
                <span class="badge bg-primary mb-3 px-3 py-2 rounded-pill">
                    <i class="fas fa-tag me-1"></i> {{ product.category }}
                </span>

                <h1 class="display-5 fw-bold text-dark mb-3">{{ product.name }}</h1>

                <div class="price-section mb-4 p-3 bg-light rounded-3">
                    <div class="d-flex align-items-center">
                        <span class="display-4 fw-bold text-success me-3">{{ product.price }} ₴</span>
                        <div class="text-muted">
<!--                            <small>В наличии</small>-->
                        </div>
                    </div>
                </div>

                <div class="description-section mb-5">
                    <h5 class="fw-semibold mb-3">
                        <i class="fas fa-info-circle me-2 text-primary"></i> Description
                    </h5>
                    <p class="text-muted lh-lg">{{ product.description }}</p>
                </div>

                <div class="action-buttons mb-4">
                    <div class="row g-2">
                        <div class="col-md-8">
                            {%if product.quantity%}
                                <a href="{% url 'products:basket_add' product.id %}" class="btn btn-success btn-lg w-100 shadow-sm">
                                    <i class="fas fa-shopping-cart me-2"></i>
                                    Add to cart
                                </a>
                            {%else%}
                                <button class="btn btn-secondary btn-lg w-100 shadow-sm" disabled>
                                    <i class="fas fa-times-circle me-2"></i>
                                    Out of Stock
                                </button>
                            {%endif%}
                        </div>
                        <div class="col-md-4">
                            <button class="btn btn-outline-secondary btn-lg w-100">
                                <i class="fas fa-heart"></i>
                            </button>
                        </div>
                    </div>

                    <div class="row g-2 mt-2">
                        <div class="col-6">
                            <button class="btn btn-outline-primary btn-sm w-100">
                                <i class="fas fa-share-alt me-1"></i> Share
                            </button>
                        </div>
                        <div class="col-6">
                            <button class="btn btn-outline-info btn-sm w-100">
                                <i class="fas fa-question-circle me-1"></i> Ask a question
                            </button>
                        </div>
                    </div>
                </div>

                <div class="quick-info">
                    <div class="row g-3">
                        <div class="col-4 text-center">
                            <div class="p-2 bg-light rounded">
                                <i class="fas fa-truck text-primary fs-4"></i>
                                <small class="d-block mt-1 text-muted">Delivery</small>
                            </div>
                        </div>
                        <div class="col-4 text-center">
                            <div class="p-2 bg-light rounded">
                                <i class="fas fa-shield-alt text-success fs-4"></i>
                                <small class="d-block mt-1 text-muted">Guarantee</small>
                            </div>
                        </div>
                        <div class="col-4 text-center">
                            <div class="p-2 bg-light rounded">
                                <i class="fas fa-headset text-info fs-4"></i>
                                <small class="d-block mt-1 text-muted">Support</small>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row mt-5">
        <div class="col-12">
            <div class="card shadow-sm border-0">
                <div class="card-header bg-white border-0 py-3">
                    <h3 class="mb-0 fw-semibold">
                        <i class="fas fa-list-ul me-2 text-primary"></i>
                        Product characteristics
                    </h3>
                </div>
                <div class="card-body p-0">
                    <div class="table-responsive">
                        <table class="table table-hover mb-0">
                            <tbody>
                                {% for key, value in product.characteristics.items %}
                                <tr>
                                    <th class="border-0 py-3 ps-4 text-muted fw-normal" style="width: 30%;">
                                        {{ key }}
                                    </th>
                                    <td class="border-0 py-3 fw-semibold">
                                        {{ value }}
                                    </td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="imageModal" tabindex="-1" aria-labelledby="imageModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header border-0">
                <h5 class="modal-title" id="imageModalLabel">{{ product.name }}</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body p-0">
                <img src="/media/{{ product.image }}" alt="{{ product.name }}" class="img-fluid w-100">
            </div>
        </div>
    </div>
</div>

<style>
.main-product-image {
    transition: transform 0.3s ease;
}

.main-product-image:hover {
    transform: scale(1.02);
}

.btn {
    transition: all 0.3s ease;
}

.btn:hover {
    transform: translateY(-2px);
    box-shadow: 0 4px 12px rgba(0,0,0,0.15);
}

.card {
    transition: transform 0.3s ease;
}

.table tbody tr:hover {
    background-color: rgba(0,123,255,0.1);
}

.quick-info .bg-light:hover {
    background-color: rgba(0,123,255,0.1) !important;
    transform: translateY(-2px);
    transition: all 0.3s ease;
}

.alert {
    animation: slideInRight 0.5s ease-out;
}

@keyframes slideInRight {
    from {
        transform: translateX(100%);
        opacity: 0;
    }
    to {
        transform: translateX(0);
        opacity: 1;
    }
}

@media (max-width: 768px) {
    .display-5 {
        font-size: 1.8rem;
    }

    .display-4 {
        font-size: 2rem;
    }

    .main-product-image {
        height: 300px !important;
    }

    #alert-container {
        top: 80px !important;
        width: 300px !important;
        right: 10px !important;
    }
}
</style>

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">

{% endblock %}

products/templates/products/index.html
{%extends 'products/base.html'%}
{% load static %}

{%block css%}
    <link href="{% static 'css/index.css' %}" rel="stylesheet">
{%endblock%}

{%block content%}
    <section>
        <div class="container">
            <div class="row">
                <div class="col-lg-6">
                        <h1 class="mt-5">ElectroHub</h1>
                        <p>
                            Welcome to our online store of appliances! 
                        </p>
                        <button id="start-purchase-btn" type="button" class="btn btn-lg">
                            <a id="start-purchase-link" href="{%url 'products:products'%}">
                                Start shopping
                            </a>
                        </button>
                </div>
            </div>
        </div>
    </section>
{%endblock%}